#!/bin/sh

echo "\nRunning variety of test cases ...\n"

seq1="ATGCT"
seq2="AGCT"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype dna

seq1="AAGACG"
seq2="CAGAGCTC"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype dna

seq1="AGTGCTGAAAGTTGCGCCAGTGAC"
seq2="AGTGCTGAAGTTCGCCAGTTGACG"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype dna

seq1="aaac"
seq2="agc"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype dna

seq1="GATTACA"
seq2="GTCGACGCA"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype dna

seq1="MKVKFV"
seq2="MKQKFV"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein

seq1="SEND"
seq2="AND"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein

seq1="AGTGCTGAAAGTTGCGCCAG"
seq2="AGTGCTGAAGTTCGCCAGTT"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype dna


echo "\nRunning complex protein alignment ...\n"

seq1="MTIPHMKYAVSKTSENKVSNTVSPTQDKDAIRKQPDDIINNDEPSHKKIKVAQPDSLRETNTTDPLGHTKAALGEVASMELKPTNDMDPLAVSAASVVSMSNDVLKPETPKGPIIISKNPSNGIFYGPSFTKRESLNARMFLKYYGAHKFLDTYLPEDLNSLYIYYLIKLLGFEVKDQALIGTINSIVHINSQERVQDLGSAISVTNVEDPLAKKQTVRLIKDLQRAINKVLCTRLRLSNFFTIDHFIQKLHTARKILVLTGAGVSTSLGIPDFRSSEGFYSKIKHLGLDDPQDVFNYNIFMHDPSVFYNIANMVLPPEKIYSPLHSFIKMLQMKGKLLRNYTQNIDNLESYAGISTDKLVQCHGSFATATCVTCHWNLPGERIFNKIRNLELPLCPYCYKKRREYFPEGYNNKVGVAASQGSMSERPPYILNSYGVLKPDITFFGEALPNKFHKSIREDILECDLLICIGTSLKVAPVSEIVNMVPSHVPQVLINRDPVKHAEFDLSLLGYCDDIAAMVAQKCGWTIPHKKWNDLKNKNFKCQEKDKGVYVVTSDEHPKTL*"
seq2="MKQKFVLPITPPSTAEKKPQTENRCNENLKPRRLLPQLKKSVRNRKPRLSYRPELNSVFDLDAYVDSTHLSKSQRHHMDRDAGFISYALNYSKRMVVVSGAGISVAAGIPDFRSSEGIFSTVNGGSGKDLFDYNRVYGDESMSLKFNQLMVSLFRLSKNCQPTKFHEMLNEFARDGRLLRLYTQNIDGLDTQLPHLSTNVPLAKPIPSTVQLHGSIKHMECNKCLNIKPFDPELFKCDDKFDSRTEIIPSCPQCEEYETVRKMAGLRSTGVGKLRPRVILYNEVHPEGDFIGEIANNDLKKRIDCLIIVGTSLKIPGVKNICRQFAAKVHANRGIVLYLNTSMPPKNVLDSLKFVDLVVLGDCQHVTSLL*"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein --gap 12 --gapext 2

seq1="MKQKFVLPITPPSTAEKKPQTENRCNENLKPRRLLPQLKKSVRNRKPRLSYRPELNSVFDLDAYVDSTHLSKSQRHHMDRDAGFISYALNYSKRMVVVSGAGISVAAGIPDFRSSEGIFSTVNGGSGKDLFDYNRVYGDESMSLKFNQLMVSLFRLSKNCQPTKFHEMLNEFARDGRLLRLYTQNIDGLDTQLPHLSTNVPLAKPIPSTVQLHGSIKHMECNKCLNIKPFDPELFKCDDKFDSRTEIIPSCPQCEEYETVRKMAGLRSTGVGKLRPRVILYNEVHPEGDFIGEIANNDLKKRIDCLIIVGTSLKIPGVKNICRQFAAKVHANRGIVLYLNTSMPPKNVLDSLKFVDLVVLGDCQHVTSLL*"
seq2="MNILLMQRIVSFILVVSQGRYFHVGELTMTMLKRPQEEESDNNATKKLKTRLTYPCILGKDKVTGKFIFPAITKDDVMNARLFLKDNDLKTFLEYFLPVEVNSIYIYFMIKLLGFDVKDKELFMALNSNITSNKERSSAELSSIHAKAEDEDELTDPLEKKHAVKLIKDLQKAINKVLSTRLRLPNFNTIDHFTATLRNAKKILVLTGAGVSTSLGIPDFRSSEGFYSKIRHLGLEDPQDVFNLDIFLQDPSVFYNIAHMVLPPENMYSPLHSFIKMLQDKGKLLRNYTQNIDNLESYAGIDPDKLVQCHGSFATASCVTCHWQIPGEKIFENIRNLELPLCPYCYQKRKQYFPMSNGNNTVQTNINFNSPILKSYGVLKPDMTFFGEALPSRFHKTIRKDILECDLLICIGTSLKVAPVSEIVNMVPSHVPQILINRDMVTHAEFDLNLLGFCDDVASLVAKKCHWDIPHKKWQDLKKIDYNCTEIDKGTYKIKKQPRKKQQ*"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein --gap 12 --gapext 2

echo "\nRunning GSA on same sequences with different gap and extention penalties ...\n"

seq1="MNILLMQRIVSFILVVSQGRYFHVGELTMTMLKRPQEEESDNNATKKLKTRLTYPCILGKDKVTGKFIFPAITKDDVMNARLFLKDNDLKTFLEYFLPVEVNSIYIYFMIKLLGFDVKDKELFMALNSNITSNKERSSAELSSIHAKAEDEDELTDPLEKKHAVKLIKDLQKAINKVLSTRLRLPNFNTIDHFTATLRNAKKILVLTGAGVSTSLGIPDFRSSEGFYSKIRHLGLEDPQDVFNLDIFLQDPSVFYNIAHMVLPPENMYSPLHSFIKMLQDKGKLLRNYTQNIDNLESYAGIDPDKLVQCHGSFATASCVTCHWQIPGEKIFENIRNLELPLCPYCYQKRKQYFPMSNGNNTVQTNINFNSPILKSYGVLKPDMTFFGEALPSRFHKTIRKDILECDLLICIGTSLKVAPVSEIVNMVPSHVPQILINRDMVTHAEFDLNLLGFCDDVASLVAKKCHWDIPHKKWQDLKKIDYNCTEIDKGTYKIKKQPRKKQQ*"
seq2="MTSVSPSPPASRSGSMCSDLPSSLQTEKLAHIIGLDADDEVLRRVTKQLSRSRRIACLTGAGISCNAGIPDFRSSDGLYDLVKKDCSQYWSIKSGREMFDISLFRDDFKISIFAKFMERLYSNVQLAKPTKTHKFIAHLKDRNKLLRCYTQNIDGLEESIGLTLSNRKLPLTSFSSHWKNLDVVQLHGDLKTLSCTKCFQTFPWSRYWSRCLRRGELPLCPDCEALINKRLNEGKRTLGSNVGILRPNIVLYGENHPSCEIITQGLNLDIIKGNPDFLIIMGTSLKVDGVKQLVKKLSKKIHDRGGLIILVNKTPIGESSWHGIIDYQIHSDCDNWVTFLESQIPDFFKTQDQIKKLRQLKREASDLRKQMKAQKDSIGTPPTTPLRTAQGIDIQGNNELNTKIKSLNTVKRKILSPENSSEEDEEENLDTRKRAKIRPTFGDNQAS*"
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein --gap 12 --gapext 2 --outtype onlyscore
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein --gap 10 --gapext 0.5 --outtype onlyscore
time ./gsa-go --seq1 $seq1 --seq2 $seq2 --seqtype protein --gap 16 --gapext 4 --outtype onlyscore